In [15]:
import pandas as pd
import numpy as np

file_path = "/Users/sabari/Documents/DS/GUVI/dspatrol/PatrolIQ-Smart_Safety_Analytics_Platform-main/data/Crime_sample.csv"

df = pd.read_csv(file_path)

print(df.shape)
df.head()

(500000, 22)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13307269,JG540388,12/14/2023 12:01:00 AM,001XX S TROY ST,0820,THEFT,$500 AND UNDER,VACANT LOT / LAND,False,False,...,28.0,27.0,06,1155371.0,1898949.0,2023,12/22/2023 03:41:15 PM,41.878520,-87.704974,"(41.878519796, -87.704973708)"
1,11339480,JB295964,06/06/2018 05:03:00 PM,003XX S HOMAN AVE,1330,CRIMINAL TRESPASS,TO LAND,SIDEWALK,True,False,...,28.0,27.0,26,1153781.0,1897987.0,2018,06/13/2018 04:15:47 PM,41.875912,-87.710838,"(41.875911762, -87.710837503)"
2,2856772,HJ520501,07/25/2003 04:45:00 PM,001XX E DELAWARE PL,0870,THEFT,POCKET-PICKING,HOTEL/MOTEL,False,False,...,42.0,8.0,06,1177786.0,1906673.0,2003,02/28/2018 03:56:25 PM,41.899235,-87.622436,"(41.899235024, -87.622436193)"
3,11912488,JC535868,11/14/2019 08:00:00 AM,031XX S SHIELDS AVE,1110,DECEPTIVE PRACTICE,BOGUS CHECK,"SCHOOL, PRIVATE, BUILDING",False,False,...,11.0,34.0,11,1174469.0,1884050.0,2019,12/08/2019 03:57:40 PM,41.837231,-87.635295,"(41.837230767, -87.635295009)"
4,10941360,JA259248,05/11/2017 11:18:00 AM,008XX N LOCKWOOD AVE,1821,NARCOTICS,MANU/DEL:CANNABIS 10GM OR LESS,SIDEWALK,True,False,...,37.0,25.0,18,1140872.0,1904987.0,2017,02/10/2018 03:50:01 PM,41.895368,-87.758063,"(41.895367769, -87.75806298)"

In [16]:
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    500000 non-null  int64
 1   Case Number           500000 non-null  object
 2   Date                  500000 non-null  object
 3   Block                 500000 non-null  object
 4   IUCR                  500000 non-null  object
 5   Primary Type          500000 non-null  object
 6   Description           500000 non-null  object
 7   Location Description  499113 non-null  object
 8   Arrest                500000 non-null  bool
 9   Domestic              500000 non-null  bool
 10  Beat                  500000 non-null  int64
 11  District              499998 non-null  float64
 12  Ward                  463897 non-null  float64
 13  Community Area        463955 non-null  float64
 14  FBI Code              500000 non-null  object
 15  X Coordinate          494426 non-null  float64
 16  Y Coordinate          494426 non-null  float64
 17  Year                  500000 non-null  int64
 18  Updated On            500000 non-null  object
 19  Latitude              494426 non-null  float64
 20  Longitude             494426 non-null  float64
 21  Location              494426 non-null  object
dtypes: bool(2), float64(7), int64(3), object(10)
memory usage: 77.2+ MB

,ID,Beat,District,Ward,Community Area,X Coordinate,Y Coordinate,Year,Latitude,Longitude
count,5.000000e+05,500000.000000,499998.000000,463897.000000,463955.000000,4.944260e+05,4.944260e+05,500000.000000,494426.000000,494426.000000
mean,7.583117e+06,1183.249840,11.301855,22.799443,37.396625,1.164688e+06,1.885925e+06,2011.151972,41.842571,-87.671172
std,3.819175e+06,704.075611,6.967469,13.857109,21.573364,1.668469e+04,3.213667e+04,7.181056,0.088406,0.060542
min,6.460000e+02,111.000000,1.000000,1.000000,0.000000,0.000000e+00,0.000000e+00,2001.000000,36.619446,-91.686566
25%,4.099536e+06,621.000000,6.000000,10.000000,23.000000,1.153112e+06,1.859109e+06,2005.000000,41.768760,-87.713156
50%,7.581444e+06,1034.000000,10.000000,23.000000,32.000000,1.166240e+06,1.891040e+06,2010.000000,41.856703,-87.665426
75%,1.100664e+07,1731.000000,17.000000,34.000000,56.000000,1.176392e+06,1.909395e+06,2017.000000,41.907037,-87.628103
max,1.412300e+07,2535.000000,31.000000,50.000000,77.000000,1.205119e+06,1.951622e+06,2026.000000,42.022910,-87.524529

In [17]:
df.dtypes

ID                        int64
Case Number              object
Date                     object
Block                    object
IUCR                     object
Primary Type             object
Description              object
Location Description     object
Arrest                     bool
Domestic                   bool
Beat                      int64
District                float64
Ward                    float64
Community Area          float64
FBI Code                 object
X Coordinate            float64
Y Coordinate            float64
Year                      int64
Updated On               object
Latitude                float64
Longitude               float64
Location                 object
dtype: object

In [4]:
df.isnull().sum()

ID                          0
Case Number                 0
Date                        0
Block                       0
IUCR                        0
Primary Type                0
Description                 0
Location Description      887
Arrest                      0
Domestic                    0
Beat                        0
District                    2
Ward                    36103
Community Area          36045
FBI Code                    0
X Coordinate             5574
Y Coordinate             5574
Year                        0
Updated On                  0
Latitude                 5574
Longitude                5574
Location                 5574
dtype: int64

In [18]:
missing_percent = df.isnull().sum()/len(df)*100
missing_percent.sort_values(ascending=False)

Ward                    7.2206
Community Area          7.2090
Location                1.1148
Longitude               1.1148
Latitude                1.1148
Y Coordinate            1.1148
X Coordinate            1.1148
Location Description    0.1774
District                0.0004
Domestic                0.0000
Beat                    0.0000
Case Number             0.0000
Arrest                  0.0000
Description             0.0000
FBI Code                0.0000
Primary Type            0.0000
IUCR                    0.0000
Year                    0.0000
Updated On              0.0000
Block                   0.0000
Date                    0.0000
ID                      0.0000
dtype: float64

In [19]:
df = df.dropna(subset=[
    'Latitude','Longitude',
    'X Coordinate','Y Coordinate','Location'
])

In [21]:
df['Ward'].fillna(df['Ward'].mode()[0], inplace=True)

In [22]:
df['Community Area'].fillna(
    df['Community Area'].mode()[0],
    inplace=True
)

In [23]:
df['Location Description'].fillna(
    df['Location Description'].mode()[0],
    inplace=True
)

In [24]:
df['District'].fillna(df['District'].mode()[0], inplace=True)

In [25]:
df.isnull().sum()

ID                      0
Case Number             0
Date                    0
Block                   0
IUCR                    0
Primary Type            0
Description             0
Location Description    0
Arrest                  0
Domestic                0
Beat                    0
District                0
Ward                    0
Community Area          0
FBI Code                0
X Coordinate            0
Y Coordinate            0
Year                    0
Updated On              0
Latitude                0
Longitude               0
Location                0
dtype: int64

In [26]:
df['Community Area'].value_counts()

Community Area
25.0    63766
8.0     16593
43.0    15054
28.0    14263
23.0    14097
        ...
55.0      997
12.0      847
47.0      685
9.0       469
0.0         6
Name: count, Length: 78, dtype: int64

In [27]:
save_path = "/Users/sabari/Documents/DS/GUVI/dspatrol/PatrolIQ-Smart_Safety_Analytics_Platform-main/data/Crime_Clean.csv"
df.to_csv(save_path, index=False)

print("Clean Dataset Saved Successfully ✅")

Clean Dataset Saved Successfully ✅